spring.application.name=HireFlow
spring.datasource.url=jdbc:postgresql://localhost:54320/hireflow
spring.datasource.username=sa
spring.datasource.password=myd@tabasepostgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Flyway (si estás usando)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
