services:
  postgres-dev:
    container_name: postgres-dev
    image: postgres:16
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: myd@tabasepostgres
      POSTGRES_DB: hireflow
    volumes:
      - c:\postgres\postgres-dev-data\data:/var/lib/postgresql/data
      - c:\SpringBoot\HireFlow\docker\init-scripts:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 5120M
        reservations:
          cpus: "1.5"
          memory: 5120M
